# Generated by Django 4.2.6 on 2023-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0003_chirp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
