# Generated by Django 4.2.6 on 2023-11-02 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirper', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='chirp_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
